# 3 NumPy Arrays
## 3.1 1D NumPy Arrays

In [3]:
import numpy as np

In [56]:
list = [20, 7, 9, 12, 31, 17, 4, 50, 39, 35]

In [57]:
arr = np.array(list)

In [18]:
print(arr*4)

[ 80  28  36  48 124  68  16 200 156 140]


In [19]:
print(np.mean(arr))

22.4


In [20]:
print(np.median(arr))

18.5


In [21]:
print(np.std(arr))

14.725488107359974


In [24]:
print(f"The smallest value is at position {np.argmin(arr)} and the largest value is position {np.argmax(arr)}.")

The smallest value is at position 6 and the largest value is position 7.


In [27]:
print(arr[6], arr[7])

4 50


In [29]:
print(np.min(arr))

4


In [30]:
print(np.max(arr))

50


No, they don't match the values when we called argmin and argmax. That is because argmin and argmax return the index (position) of the minimum and maximun values, not the values themselves.

In [58]:
filter = arr > 20
new_array = arr[filter]
print(new_array)

[31 50 39 35]


## 3.2 2D NumPy Arrays

In [94]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]

Matrix = np.array(matrix)

In [73]:
print(f"Matrix has {Matrix.shape[0]} rows and {Matrix.shape[1]} columns.")

Matrix has 3 rows and 4 columns.


In [74]:
print(Matrix[:, 2])

[17 14 19]


In [75]:
print(Matrix[1, :])

[ 8 21 14  3]


In [77]:
print(Matrix*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [97]:
for col in Matrix.T:
    column_mean = np.mean(col)
    print(column_mean)

6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667


In [91]:
mean_array = np.mean(Matrix)
mean_array

np.float64(11.5)

In [92]:
for row in Matrix:
    max_val = np.max(row)
    print(max_val)

17
21
19


In [98]:
for column in Matrix.T: # have to do transpose!
    min_val = np.min(column)
    print(min_val)

5
12
14
3


In [100]:
print(Matrix.flatten()) # Makes it a 1D array.

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [104]:
argmin = np.argmin(Matrix.flatten())

In [112]:
argmax = np.argmax(Matrix.flatten())

In [119]:
max_pos = np.unravel_index(argmax, Matrix.shape)
min_pos = np.unravel_index(argmin, Matrix.shape)

In [120]:
filtered = Matrix[Matrix > 15]
print("Values greater than 15:", filtered)

Values greater than 15: [17 21 19]


In [121]:
sorted_matrix = np.sort(Matrix, axis=1)
print("Sorted matrix:\n", sorted_matrix)

Sorted matrix:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


# 4 Prime Star Systems

In [123]:
# this isn't the name of the variable it says to use in the homework but for the 
# sake of preventing redunancy...
star_arr = np.array([
    [2,3,5],
    [14,6,8],
    [11,13,17],
    [7,10,13]
])

In [126]:
def is_prime(n):
    if n < 2:
        return False

    sieve = [True] * (n + 1)
    sieve[0] = sieve[1] = False

    for i in range(2, int(n**0.5) + 1):
        if sieve[i]:
            for j in range(i * i, n + 1, i):
                sieve[j] = False

    return sieve[n]

In [137]:
def print_prime_rows(array):
    for row in star_arr:
        for i in row:
            if is_prime(i) == True:
                print(row)
                break

In [138]:
print_prime_rows(star_arr)

[2 3 5]
[11 13 17]
[ 7 10 13]


# 5 Let's Play Checkers!

In [33]:
zeroes = np.zeros(shape=(8,8))
zeroes

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
zeroes[0::2, ::2] = 1         # odd rows, every other column
print(zeroes)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
zeroes[1::2, 1::2] = 1
print(zeroes)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [37]:
reverse_check = np.abs(zeroes - 1)
print(reverse_check)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 6 The Expanding Universe

In [44]:
def expand(string, n):
    spaces = " " * n
    return spaces.join(string)

In [47]:
expand("universe",1)

'u n i v e r s e'

# 7 Second-Brightest Star

In [48]:
stars = np.random.randint(500, 2000, (5,5))
stars

array([[ 857, 1118, 1303,  535, 1495],
       [1243, 1588,  570,  799,  595],
       [1461,  913, 1038, 1233, 1754],
       [ 563, 1929, 1197, 1120, 1303],
       [1498,  723, 1767, 1806, 1107]])

In [54]:
def second_brightest(array):
    for row in array:
        second_brightest = sorted(row, reverse=True)
        print(second_brightest[1])

second_brightest(stars)

1303
1243
1461
1303
1767
